import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

G.add_node('Solapur')
G.add_node('Pune')
G.add_node('Kolhapur')
G.add_node('Satara')
G.add_node('Mahabaleshwar')
G.add_node('Latur')
G.add_node('Nanded')
G.add_node('Aurangabad')
G.add_node('Parbhani')
G.add_node('Mumbai')
G.add_node('Navi Mumbai')
G.add_node('AhmedNagar')
G.add_node('Nashik')
G.add_node('Beed')
G.add_node('Dhule')
G.add_node('Jalna')

G.add_edge('Solapur','Pune', weight=253)
G.add_edge('Solapur','Latur', weight=123)
G.add_edge('Solapur','Kolhapur',weight=285)
G.add_edge('Solapur','Satara',weight=249)
G.add_edge('Solapur','Beed',weight=180)
G.add_edge('Latur','Nanded',weight=144)
G.add_edge('Nanded','Parbhani',weight=71)
G.add_edge('Parbhani','Beed',weight=147)
G.add_edge('Parbhani','Jalna',weight=138)
G.add_edge('Jalna','Aurangabad',weight=60)
G.add_edge('Jalna','Dhule',weight=209)
G.add_edge('Aurangabad','Dhule',weight=151)
G.add_edge('Aurangabad','Beed',weight=126)
G.add_edge('Dhule','Nashik',weight=158)
G.add_edge('Nashik','AhmedNagar',weight=157)
G.add_edge('Nashik','Mumbai',weight=167)
G.add_edge('Mumbai','Navi Mumbai',weight=22)
G.add_edge('Mumbai','AhmedNagar',weight=254)
G.add_edge('AhmedNagar','Beed',weight=128)
G.add_edge('AhmedNagar','Pune',weight=122)
G.add_edge('Navi Mumbai','Mahabaleshwar',weight=201)
G.add_edge('Navi Mumbai','Pune',weight=127)
G.add_edge('Mahabaleshwar','Satara',weight=68)
G.add_edge('Satara','Kolhapur',weight=122)
G.add_edge('Satara','Pune',weight=110)
G.add_edge('Pune','Kolhapur',weight=230)

nx.draw(G, with_labels =1)

plt.show()